image: Visual Studio 2017
version: 3.2.2-{build}
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    NPGSQL_TEST_DB: Host=localhost;Database=postgres;Username=postgres;Password=Password12!
    PGUSER: postgres
    PGPASSWORD: Password12!
    POSTGIS_EXE: postgis-bundle-pg95x64-setup-2.3.2-1.exe
cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
  - 'C:\projects\npgsql\packages -> **\*.csproj'  # For VSIX
  - $(POSTGIS_EXE)
shallow_clone: true
install:
  # Turn on prepared (distributed) transactions
  - ps: (Get-Content 'C:\Program Files\PostgreSQL\9.5\data\postgresql.conf').replace('#max_prepared_transactions = 0', 'max_prepared_transactions = 10') | Set-Content 'C:\Program Files\PostgreSQL\9.5\data\postgresql.conf'
  # Turn on SSL with a self-signed certificate
  - 'xcopy .build\server.crt "C:\Program Files\PostgreSQL\9.5\data" /y'
  - 'xcopy .build\server.key "C:\Program Files\PostgreSQL\9.5\data" /y'
  - ps: (Get-Content 'C:\Program Files\PostgreSQL\9.5\data\postgresql.conf').replace('#ssl = off', 'ssl = on') | Set-Content 'C:\Program Files\PostgreSQL\9.5\data\postgresql.conf'
  - powershell .build\postgis.ps1
  # PostGIS
  #- ps: (New-Object Net.WebClient).DownloadFile('http://download.osgeo.org/postgis/windows/pg95/postgis-bundle-pg95x64-setup-2.3.2-1.exe', 'c:\postgis.exe')
  #- c:\postgis.exe /S /D="C:\Program Files\PostgreSQL\9.5"
services:
  - postgresql
before_build:
  - '"C:\Program Files\PostgreSQL\9.5\bin\psql" -c "CREATE EXTENSION postgis"'
  - appveyor-retry dotnet restore -v Minimal
  - appveyor-retry nuget restore Npgsql.sln   # For VSIX
build_script:
  - dotnet build "src\Npgsql" -c ReleaseOptimizedCryptography
  - dotnet build "test\Npgsql.Tests" -c Debug
  - msbuild src\VSIX\VSIX.csproj /p:Configuration=Release
  - msbuild src\MSI\MSI.wixproj /p:Configuration=Release
after_build:
  - ps: $env:padded_build_number = $env:appveyor_build_number.PadLeft(5, '0')
  - dotnet pack src\Npgsql\Npgsql.csproj -c ReleaseOptimizedCryptography --version-suffix ci-%PADDED_BUILD_NUMBER%
test:
  assemblies:
    - test\Npgsql.Tests\bin\Debug\net451\Npgsql.Tests.exe
artifacts:
  - path: 'src\Npgsql\bin\**\*.nupkg'
    name: Nuget
  - path: 'src\VSIX\bin\**\*.vsix'
    name: Visual Studio Extension
  - path: 'src\MSI\bin\**\*.msi'
    name: MSI Installer
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/npgsql-unstable/api/v2/package
    api_key:
      secure: kiMn9uBvgMa5EtEmTIhNBFUfyatiATnhkgx5Xj/1EsmKTtEkUv+hJAQs0L3VGzPw
    artifact: /.*\.nupkg/
    skip_symbols: true
    #skip_symbols: false
    #symbol_server: https://your.symbol.server/feed

